### PR TITLE
Updates to SW and cleanup of older items

### PR DESCRIPTION
**Pull request by coogie**
1. Removes html5shiv. Gone, but never forgotten ✌️ 
2. Update and un-minify Normalize to `1.1.0`
3. Overhaul ServiceWorker to make use of Workbox instead
4. Add GA custom dimension for tracking network status of events

N.B. @shaneog -- I don't have access rights to set up a dimension in GA. Could you take care of that?  
(This MR is working on the assumption that [this will be `dimension1`](https://github.com/coogie/whatismyviewport/pull/46/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R90). I can't remember if we have any dimensions already)
https://support.google.com/analytics/answer/2709829#set_up_custom_dimensions&zippy=%2Cin-this-article
```
Name: Network Status
Scope: Hit
Active: true
```

### CODE REVIEW

**Comment by shaneog** [comment]
Nice! Dimension created in GA.
Also, do we need to migrate to GA4 at some point?

**Review by shaneog — APPROVED** [review]

**Comment by coogie** [comment]
Agh, probably, but we don't really make use of any features that would make it worthwhile do we?

**Comment by shaneog** [comment]
I doubt it - in fact I'd be in favor of removing it overall. I wonder could we get sufficient stats via GitHub or Cloudflare for example?

**Comment by coogie** [comment]
Same here, for various reasons

I think the GitHub stats only track traffic to the repo itself rather than GitHub Pages traffic. Cloudflare might be enough if only care about the basic usage.

Although I don't think we could track offline

**Pull request merged**
